name: custom_pin_keyboard
description: The best flutter package that gives you a custom keyboard for one time password widgets, transaction pin widgets and simple login widgets. Shortcomings of other packages were taken into account!
homepage: https://pub.dev/packages/custom_pin_keyboard
repository: https://github.com/arrrtem22/custom_pin_keyboard/
issue_tracker: https://github.com/arrrtem22/custom_pin_keyboard/issues
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"