name: custom_pin_keyboard
description: The best flutter package that gives you a custom keyboard for one time password widgets, transaction pin widgets and simple login widgets
homepage: https://pub.dev/packages/custom_pin_keyboard
repository: https://github.com/arrrtem22/custom_pin_keyboard/
issue_tracker: https://github.com/arrrtem22/custom_pin_keyboard/issues
version: 0.0.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"